version: '3.8'

services:
  fullstack-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      # Mount data directory to persist todos
      - ./data:/app/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: fullstack-todo-app
    
  # Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - fullstack-app
  #   restart: unless-stopped
