name: CI/CD

# Exclude the workflow to run on changes to docs and deployment configs
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'k8s/**'
      - 'README.md'
      - 'KIND-DEPLOYMENT.md'
      - 'helm/'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci || npm install

    - name: Build
      run: npm run build || echo "No build script defined, skipping build step"

    - name: Test
      run: npm test || echo "No tests defined, skipping test step"
  
  code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci || npm install

    - name: Lint code
      run: npm run lint || echo "No linting configured, skipping lint step"
  
  push:
    runs-on: ubuntu-latest
    needs: [build, code-quality]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push action
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          vanshitsharma07/fullstack-todo-app:${{github.run_id}}
          vanshitsharma07/fullstack-todo-app:latest

  update-k8s-manifest:
    runs-on: ubuntu-latest
    needs: push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.token }}

    - name: Update image tag in K8s manifest
      run: |
        sed -i 's|image: vanshitsharma07/fullstack-todo-app:.*|image: vanshitsharma07/fullstack-todo-app:${{github.run_id}}|' k8s-manifest.yaml

    - name: Commit and push changes
      run: |
        git config --global user.email "vanshitsharma2006@gmail.com"
        git config --global user.name "Vanshit Sharma"
        git add k8s-manifest.yaml
        git commit -m "Update image tag in K8s manifest to ${{github.run_id}}"
        git push
